-- =============================================================================
-- Migration 0004: Add multiple-choice quiz tables
-- =============================================================================
-- Adds the quiz methodology: multiple-choice questions generated by an LLM,
-- then graded WITHOUT an LLM by comparing the learner's chosen index against
-- the stored correct index. This is what distinguishes quiz from the other
-- three methodologies already present — Socratic is a dialogue and Feynman is
-- free-text scored by the model, whereas a quiz answer is objectively
-- checkable, so grading must never cost a token or depend on model mood.
--
-- Two tables:
--   * quiz_questions -- the generated question, its choices, and the answer
--   * quiz_attempts  -- one row per answer submitted by a learner
--
-- Scoped to a study_set, consistent with socratic_sessions and
-- feynman_evaluations. Cascade behavior is likewise consistent: deleting a
-- study_set or user removes their questions and attempts rather than leaving
-- orphans.
--
-- `source` records where a question came from. 'topic' means it was generated
-- from free text the user supplied; 'knowledge_store' means it was generated
-- from a concept node already in the Chiron Knowledge Store, in which case
-- source_node_id points back at that node. There is deliberately NO foreign
-- key on source_node_id: the Knowledge Store is a separate database
-- (chiron_ks) on the same cluster, and Postgres cannot enforce referential
-- integrity across databases. The column is a traceability breadcrumb, not a
-- constraint.
--
-- Modelled with TEXT + CHECK rather than a Postgres ENUM, matching
-- socratic_messages.role. Both conventions exist in this schema; the closed
-- two-value set read and written directly by handlers is the role case, not
-- the ai_interaction_type case.
--
-- This is a plain SQL authoring artifact. Apply it with:
--   psql -h 127.0.0.1 -p 5432 -U postgres -d mnemosyne -f <this file>
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Table: quiz_questions
-- ---------------------------------------------------------------------------
CREATE TABLE quiz_questions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    set_id          UUID NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    question        TEXT NOT NULL,
    choices         JSONB NOT NULL,   -- array of strings, one per option
    correct_index   INTEGER NOT NULL, -- 0-based index into choices
    source          TEXT NOT NULL CHECK (source IN ('topic', 'knowledge_store')),
    source_node_id  UUID,             -- ks.nodes(id) when source='knowledge_store'; no FK, different database
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- choices must be a JSON array, not an object or scalar.
    CONSTRAINT quiz_questions_choices_is_array
        CHECK (jsonb_typeof(choices) = 'array'),

    -- A multiple-choice question with fewer than two options is not a choice.
    CONSTRAINT quiz_questions_choices_min_length
        CHECK (jsonb_array_length(choices) >= 2),

    -- The answer must actually be one of the offered options. Enforced in the
    -- database as well as the handler: a correct_index pointing past the end
    -- of choices would make the question permanently unanswerable, and that
    -- is worth catching at the last line of defence.
    CONSTRAINT quiz_questions_correct_index_in_range
        CHECK (correct_index >= 0 AND correct_index < jsonb_array_length(choices)),

    -- source_node_id is present exactly when the question came from the
    -- Knowledge Store. Same shape as ks.extracted_concepts'
    -- extracted_node_id_iff_accepted constraint.
    CONSTRAINT quiz_questions_node_id_iff_knowledge_store
        CHECK ((source = 'knowledge_store') = (source_node_id IS NOT NULL))
);

CREATE INDEX idx_quiz_questions_set_id ON quiz_questions (set_id);
CREATE INDEX idx_quiz_questions_source ON quiz_questions (source);

-- ---------------------------------------------------------------------------
-- Table: quiz_attempts
-- ---------------------------------------------------------------------------
-- One row per submitted answer. is_correct is stored rather than derived on
-- read: it is computed once at answer time from the question as it existed
-- then, so later edits to a question cannot retroactively rewrite a learner's
-- history.
CREATE TABLE quiz_attempts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id     UUID NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    selected_index  INTEGER NOT NULL CHECK (selected_index >= 0),
    is_correct      BOOLEAN NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_quiz_attempts_question_id ON quiz_attempts (question_id);
CREATE INDEX idx_quiz_attempts_user_id ON quiz_attempts (user_id);
CREATE INDEX idx_quiz_attempts_user_created ON quiz_attempts (user_id, created_at);

-- ---------------------------------------------------------------------------
-- Extend ai_interaction_type for quiz generation cost tracking
-- ---------------------------------------------------------------------------
-- Quiz generation calls the LLM and costs real tokens, so it is logged in
-- ai_interactions like the other three. Grading does NOT appear here because
-- grading never calls a model.
ALTER TYPE ai_interaction_type ADD VALUE IF NOT EXISTS 'quiz_generation';
