-- =============================================================================
-- Migration 0005: Track where a card came from
-- =============================================================================
-- Adds provenance to `cards`, so a flashcard generated from a Knowledge Store
-- concept can be told apart from one typed by hand or generated from free
-- text. This is what POST /cards/from_node needs in order to be idempotent:
-- without a stable link back to the originating node there is nothing to
-- deduplicate on.
--
-- Mirrors the shape already used by quiz_questions (migration 0004), including
-- the deliberate absence of a foreign key on the node id: the Knowledge Store
-- is a separate database (chiron_ks) on the same cluster, and Postgres cannot
-- enforce referential integrity across databases. The column is a traceability
-- breadcrumb, not a constraint.
--
-- Backfill note: existing rows take the DEFAULT 'manual'. That is correct for
-- cards created through POST /cards, but NOT for cards generated by
-- POST /study_sets/{set_id}/generate_cards before this migration — those were
-- AI-generated from free text and are indistinguishable from hand-typed ones
-- in the data as it stands, because nothing recorded the difference at the
-- time. Going forward generate.rs stamps source='topic'; historical rows stay
-- 'manual' and cannot be reclassified after the fact.
--
-- This is a plain SQL authoring artifact. Apply it with:
--   psql -h 127.0.0.1 -p 5432 -U postgres -d mnemosyne -f <this file>
-- =============================================================================

ALTER TABLE cards
    ADD COLUMN source TEXT NOT NULL DEFAULT 'manual'
        CHECK (source IN ('manual', 'topic', 'knowledge_store')),
    ADD COLUMN source_node_id UUID;  -- ks.nodes(id) when source='knowledge_store'; no FK, different database

-- The node id is present exactly when the card came from the Knowledge Store.
-- Same shape as quiz_questions_node_id_iff_knowledge_store.
ALTER TABLE cards
    ADD CONSTRAINT cards_node_id_iff_knowledge_store
        CHECK ((source = 'knowledge_store') = (source_node_id IS NOT NULL));

-- One card per concept per study set. This is the idempotency key for
-- POST /cards/from_node: calling it twice for the same node in the same set
-- must not produce a second card.
--
-- Postgres treats NULLs as distinct in a unique index, so this constrains only
-- rows that actually name a node. Manual and topic-generated cards all carry
-- source_node_id = NULL and are unaffected — a set can hold any number of them.
ALTER TABLE cards
    ADD CONSTRAINT cards_set_node_unique
        UNIQUE (set_id, source_node_id);

-- ---------------------------------------------------------------------------
-- Extend ai_interaction_type for card-from-node generation
-- ---------------------------------------------------------------------------
-- Generating the question/answer pair from a node's title and summary calls the
-- LLM and costs real tokens, so it is logged like the other generating paths.
ALTER TYPE ai_interaction_type ADD VALUE IF NOT EXISTS 'card_from_node_generation';
